# Generated by Django 3.0.2 on 2020-01-15 11:10

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temat', models.TextField()),
                ('content', froala_editor.fields.FroalaField()),
            ],
        ),
    ]
